### ISSUE TITLE
The report output is incorrect

### ISSUE THREAD

**Issue by lucipacurar** [iernie/gulp-tslint-teamcity#1]
Hi,

I'm trying to generate TeamCity friendly reports but all I get is this output:

```
##teamcity[testFailed name='(function () {|r|n                                  return o.startPosition.line;|r|n                                    }1,function () {|r|n
                               return o.startPosition.character;|r|n                                }1) Missing trailing comma' message='|[trailing-comma|] Missing trailing comma' detailed='']
```

My task looks like this:

```
gulp.task("lint", function () {
    return gulp.src(['./App/**/*.ts', '!./App/bower_components/**/*.ts', '!./App/libs/**/*.ts'])
        .pipe(tslint())
        .pipe(tslint.report(teamcity, {
            emitError: false
        }));
});
```

Any idea about what am I doing wrong? Thanks!

**Comment by iernie** [comment]
Hi

I had no idea there was an issue here. Are you still experiencing this issue?

**Comment by lucipacurar** [comment]
Hi

No, I'm not getting it anymore after the fixing it in my fork :) I used my fork until now and I'm using TSLint 3.12. I guess we also need to check if it works correctly with TSLint 4.x.

**Comment by iernie** [comment]
Found out that with tslint 4.x, gulp-tslint 7.x and tslint-teamcity-reporter 2.x you do not need this package anymore. I've updated the readme with instructions :)

**Comment by iernie** [comment]
@lucassp I've updated the package with your PR though in case you want to use it from npm :)
